# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38002a229581ee44261130bdf27facfb82f250ca81ab6476b7883ff18110156c60b298cee5bce9aa97d18aaedbd72eaf29a9f9181d824d6609d549b589fccba2

test:
  secret_key_base: 6d3f422b2ce496938a8845608d3f4c91ffe08e7a60bda869aaaa5a49c125276ff5af16c6d67c9007aef167deb4b04e37ae1867936dcf8010907f4078e6df6c27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
